### ISSUE TITLE
не работает адрес /register/

### ISSUE THREAD

**Issue by biomesser** [natkaida/django#2]
выдает ошибку:
In template /home/creck/Documents/samplesite_3/proglib/my_site_copy/django-main/step2/my_site/blog/templates/blog/base.html, error at line 11

django.template.exceptions.TemplateDoesNotExist: bootstrap4/uni_form.html
[19/Feb/2023 21:56:46] "GET /register/ HTTP/1.1" 500 174355

Скажите пожалуйста, в чем может быть проблема?
Спасибо!!

**Comment by natkaida** [comment]
Эта ошибка связана со встроенным набором шаблонов Bootstrap для Crispy forms. Проверьте файл settings.py, у вас должны быть указаны:
crispy_forms в INSTALLED_APPS;
CRISPY_TEMPLATE_PACK = 'bootstrap4'

**Comment by biomesser** [comment]
Благодарю за ответ!
Все указанные стоки у меня в сеттингсах присутствуют, но это не спасает.

Причем не работает только ссылка на  register/

**Comment by natkaida** [comment]
А в base.html ссылка на register есть?
` <a class="nav-item nav-link" href="{% url 'register' %}">Регистрация</a>`
Во views.py есть def register(request)?
В users/forms.py есть class UserRegisterForm(UserCreationForm)?

**Comment by biomesser** [comment]
да, все на месте. Я это все нагуглил и проверил заранее.
И интересный с моей точки зрения момент! браузер показывает (подсвечивает) в отчете об ошибке один и тот же диапазон символов в 11 строке базового шаблона.


  | <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
-- | --

**Comment by biomesser** [comment]
у меня, по всей видимости, какие-то системные проблемы с бутстрапом

**Comment by natkaida** [comment]
Если хотите, загрузите код на Гитхаб, или просто пришлите архив всех файлов (без venv и базы) на `` - посмотрю, в чем дело.

**Comment by biomesser** [comment]
Спасибо!!
Отправил.

пн, 20 февр. 2023 г. в 20:04, Natalia Kaida ***@***.***>:

**Comment by natkaida** [comment]
Это однозначно проблема с модулем crispy-forms. Если убрать тег `{{{ {% form|crispy %} }}}` страница грузится, но без формы, конечно. Посмотрю, что можно сделать - возможно, свежая версия Джанго не воспринимает последнюю версию crispy-forms.

**Comment by biomesser** [comment]
Спасибо!
Я проверял на джанго 3.2

вт, 21 февр. 2023 г. в 00:06, Natalia Kaida ***@***.***>:

**Comment by natkaida** [comment]
Проверила последнюю работающую конфигурацию:
Django 4.1.4
Crispy forms 1.14.0
В общем, проще всего будет удалить формы версии 2.0 (скорее всего, у вас именно эта версия), и установить 1.14.0.

**Comment by biomesser** [comment]
Спасибо большое!
джанго 3.2 + django-crispy-forms 1.14.0  Работает корректно!

вт, 21 февр. 2023 г. в 12:54, Natalia Kaida ***@***.***>:

**Comment by natkaida** [comment]
И Вам спасибо, что сообщили о проблеме. В следующих проектах лучше буду использовать обычные формы:)
